compute_environment: LOCAL_MACHINE
debug: false
main_process_port: 12121
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  zero_stage: 1
distributed_type: DEEPSPEED
downcast_bf16: 'yes'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false